server:
    port: 6020
spring:
    application:
        name: config    
    cloud:
        config:
            label: master
            server:
                git:
                    uri: https://github.com/zengmoss/cloud-config
                    searchPaths: cloud-config-repo
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
management:
    security:
        enabled: false
eureka:
    client:
        serviceUrl:
            defaultZone: http://DC12985.biostime.com:6010/eureka/        